source "/home/rico/.zsh/aliases"
# source "/home/rico/.fresh/build/shell.sh"
source "/home/rico/.zsh/export_list.zsh"
source "/home/rico/.cargo/env"
source "/home/rico/.zsh/scripts/awesome-fzf.zsh"
# source "/home/rico/.config/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"
